project:
  type: website
  output-dir: docs

website:
  title: "Álex Espinosa-Correa"
  image: images/banner-AEC.png
  description: "website personal de Álex Espinosa-Correa"
  favicon: images/icon-AEC.png
  site-url: https://alexespinosaco.github.io
  repo-url: https://github.com/alexespinosaco/alexespinosaco.github.io
  navbar:
    logo: images/icon-AEC.png
    background: secondary
    right: 
      - href: index.qmd
        text: home
      - href: about.qmd
        text: about
      - href: posts.qmd
        text: blog
      - href: https://github.com/alexespinosaco
        icon: github
      - href: https://www.linkedin.com/in/alexespinosaco/
        icon: linkedin
      - href: https://twitter.com/alexespinosaco
        icon: twitter
  page-footer: 
    background: secondary
    left: 
      - href: https://creativecommons.org/licenses/by-nc-sa/4.0/
        text: CC BY-NC-SA 4.0
    right: 
      - href: https://github.com/alexespinosaco
        icon: github
      - href: https://www.linkedin.com/in/alexespinosaco/
        icon: linkedin
      - href: https://twitter.com/alexespinosaco
        icon: twitter

format:
  html:
    lang: es
    theme: darkly
    css: styles.css
    toc: true
    code-link: true



