project:
  type: website

date-format: iso

execute:
    freeze: auto

lightbox: true

website:
  title: "Álex Espinosa-Correa"
  description: "website personal de Álex Espinosa-Correa"
  site-url: https://alexespinosaco.github.io
  repo-url: https://github.com/alexespinosaco/alexespinosaco.github.io
  
  image: images/banner-AEC.png
  favicon: images/icon-AEC.png
  
  page-navigation: false
  back-to-top-navigation: false
  bread-crumbs: true
  
  # cookie-consent: 
  #   type: express
  #   style: simple
  #   palette: dark

  google-analytics:
    tracking-id: "G-RN5H7WV1DJ"
    anonymize-ip: true

  open-graph:
    locale: es_ES

  twitter-card: 
    creator: "@alexespinosaco"
    card-style: summary_large_image

  navbar:
    logo: images/icon-AEC.png
    search: true

    right: 
      - href: index.qmd
        text: Inicio
      - href: cv/index.qmd
        text: Acerca
      - href: aerovagante/index.qmd
        text: Blog
      - href: https://github.com/alexespinosaco
        text: "{{< fa brands github >}}"
        # icon: github
      - href: https://www.linkedin.com/in/alexespinosaco/
        text: "{{< fa brands linkedin >}}"
        # icon: linkedin
      - href: https://mstdn.social/@alexespinosaco
        text: "{{< fa brands mastodon >}}"
        # icon: mastodon
      - href: https://www.researchgate.net/profile/Alex-Espinosa-Correa
        text: "{{< ai researchgate >}}"
      - href: aerovagante/index.xml
        text: "{{< fa rss >}}"
        # icon: rss

  page-footer: 
    left: Álex Espinosa-Correa © 2024. All content licensed  under [CC BY 4.0 {{< fa brands creative-commons >}}{{< fa brands creative-commons-by >}}](https://creativecommons.org/licenses/by/4.0/)
    right: 
      - href: https://github.com/alexespinosaco
        text: "{{< fa brands github >}}"
        # icon: github
      - href: https://www.linkedin.com/in/alexespinosaco/
        text: "{{< fa brands linkedin >}}"
        # icon: linkedin
      - href: https://mstdn.social/@alexespinosaco
        text: "{{< fa brands mastodon >}}"
        # icon: mastodon
      - href: https://www.researchgate.net/profile/Alex-Espinosa-Correa
        text: "{{< ai researchgate >}}"
      - href: aerovagante/index.xml
        text: "{{< fa rss >}}"
        # icon: rss

format:
  html:
    theme: litera
    css: styles.css
    toc: false
    code-link: true
