project:
  type: website

date-format: iso

execute:
    freeze: auto

lightbox: true

website:
  title: "Álex Espinosa-Correa"
  description: "Website personal de Álex Espinosa-Correa"
  site-url: https://alexespinosaco.github.io
  repo-url: https://github.com/alexespinosaco/alexespinosaco.github.io
  
  image: images/banner-AEC.png
  favicon: images/icon-AEC.png
  
  page-navigation: false
  back-to-top-navigation: false
  bread-crumbs: true
  
  # cookie-consent: 
  #   type: express
  #   style: simple
  #   palette: dark

  google-analytics:
    tracking-id: "G-RN5H7WV1DJ"
    anonymize-ip: true

  open-graph:
    locale: es_ES

  twitter-card: 
    creator: "@alexespinosaco"
    card-style: summary_large_image

  navbar:
    logo: images/icon-AEC.png
    search: true

    right: 
      - text: "Inicio"
        href: index.qmd
      - text: "Acerca (CV)"
        href: cv/index.qmd
      - text: "Blog"
        href: aerovagante/index.qmd
      - text: "Docencia"
        href: teaching/index.qmd
      - text: "Ponencias"
        href: talks/index.qmd
      - text: "Proyectos"
        href: projects/index.qmd
      - text: "{{< fa brands github >}}"
        # icon: github
        href: https://github.com/alexespinosaco
      - text: "{{< fa brands linkedin >}}"
        # icon: linkedin
        href: https://www.linkedin.com/in/alexespinosaco/
      - text: "{{< fa brands mastodon >}}"
        # icon: mastodon
        href: https://mstdn.social/@alexespinosaco
      - text: "{{< ai researchgate >}}"
        href: https://www.researchgate.net/profile/Alex-Espinosa-Correa
      - text: "{{< fa rss >}}"
        # icon: rss
        href: aerovagante/index.xml

  page-footer: 
    left: |
      Álex Espinosa-Correa © 2024. All content licensed under [CC BY 4.0 {{< fa brands creative-commons >}}{{< fa brands creative-commons-by >}}](https://creativecommons.org/licenses/by/4.0/)
    center: 
      - text: "{{< fa brands github >}}"
        # icon: github
        href: https://github.com/alexespinosaco
      - text: "{{< fa brands linkedin >}}"
        # icon: linkedin
        href: https://www.linkedin.com/in/alexespinosaco/
      - text: "{{< fa brands mastodon >}}"
        # icon: mastodon
        href: https://mstdn.social/@alexespinosaco
      - text: "{{< ai researchgate >}}"
        href: https://www.researchgate.net/profile/Alex-Espinosa-Correa
      - text: "{{< fa rss >}}"
        # icon: rss
        href: aerovagante/index.xml
    right: |
      Made with {{< fa brands r-project >}} and [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/)

format:
  html:
    theme: litera
    css: styles.css
    toc: false
    code-link: true
