project:
  type: website
  output-dir: docs

website:
  title: "Álex Espinosa-Corea"
  description: "website personal de Álex Espinosa-Correa"
  navbar:
    right: 
      - href: index.qmd
        text: home
      - href: about.qmd
        text: about
      - href: https://github.com/alexespinosaco
        icon: github
      - href: https://www.linkedin.com/in/alexespinosaco/
        icon: linkedin
      - href: https://twitter.com/alexespinosaco
        icon: twitter
  page-footer: 
    background: dark
    left: 
      - href: https://creativecommons.org/licenses/by-nc-sa/4.0/
        text: CC BY-NC-SA 4.0
    right: 
      - href: https://github.com/alexespinosaco
        icon: github
      - href: https://www.linkedin.com/in/alexespinosaco/
        icon: linkedin
      - href: https://twitter.com/alexespinosaco
        icon: twitter

format:
  html:
    theme: 
      dark: darkly
      light: flaty
    css: styles.css
    toc: true
    code-link: true



