---
title: "XII CCB: Investigación Reproducible con Quarto"
# subtitle: ""
# description: ""

lang: es

date: 2024-11-03

image: image.svg

citation: true

categories: 
  - Curso
  - Quarto
  - Reproducibilidad
  - Sito web
  - XII CCB

about:
  id: project
  template: jolla
  image-shape: rectangle
  links:
    - text: "{{< fa brands github >}} GitHub"
      href: https://github.com/geobota/xii-ccb-quarto/
    - text: "{{< fa link >}} Sitio web"
      href: https://geobota.github.io/xii-ccb-quarto/
---

:::{ #project}
:::

Durante el XII Congreso Colombiano de Botánica, celebrado del 4 al 8 de noviembre de 2024 en la ciudad de Popayán, Colombia, tuve el placer de impartir el curso «Investigación Reproducible con Quarto». Este curso representó un primer acercamiento a la reproducibilidad en el contexto de las investigaciones botánicas.

Desde hace algunos años, tanto Quarto como la reproducibilidad científica se han convertido en pilares fundamentales de mi trabajo. No solo porque la ciencia enfrenta una crisis de reproducibilidad, sino también porque considero que estas herramientas y enfoques transforman significativamente la manera en que estudiantes, investigadores y docentes abordan sus proyectos. Aunque en algunos campos aún se siguen métodos que datan de hace varias décadas, las nuevas tecnologías ofrecen oportunidades para mejorar estos procesos de manera más eficiente y precisa.

Toda la información relacionada con el curso está disponible en el [sitio web del curso](https://geobota.github.io/xii-ccb-quarto/).  
