---
title: CV
date: last-modified
date-format: iso

author: 
  - name: Álex Espinosa-Correa
    email: alex.espinosa@udea.edu.co 
    orcid: 0000-0002-7353-1182
address: "Medellín, Colombia"
# The following are optional
# phone: your contact number
email: alex.espinosa@udea.edu.co
github: alexespinosaco
orcid: 0000-0002-7353-1182
# osf: five character osf id
# twitter: alexespinosaco
# web: alexespinosaco.github.io/ # web address (no `https://`)

fontsize: 12pt
#fontfamily: ebgaramond-maths # default font LaTeX package https://tug.org/FontCatalogue/about.html
#mainfont: Ubuntu # if you want to use a different locally installed font
#CJKmainfont: Noto Sans CJK JP # locally installed Asian character font, must use with xelatex
fontawesome: yes

# Use the multibib extension
filters:
  - multibib

# Turn off YAML validation
validate-yaml: false

# Define list of separate bibliography files
nocite: '@*'
bibliography:
  main: references.bib
  appendix: appendix.bib
csl: apa-cv.csl

# Disable citeproc
citeproc: false

format:
  html: 
    toc: true
  quarto-cv-pdf: default
css: cv.css
---

Biólogo y candidato a doctor de la Universidad de Antioquia, especializado en el campo de la botánica y la palinología. Cuento con más de cuatro años de experiencia docente en botánica y biología general. Poseo habilidades en el manejo de diversos sistemas operativos, software de ofimática, herramientas bioinformáticas, sistemas de información geográfica (SIG), el lenguaje de programación R, así como en sistemas de publicación como Quarto y Markdown. Además, tengo dominio de técnicas y métodos botánicos, histológicos, palinológicos y de biología molecular, así como conocimientos en Ciencia Abierta y Reproducible. 

# Educación

**Doctor en Biología - Universidad de Antioquia - Medellín, Colombia** \hfill [2019-pendiente de ceremonia de grados]{.cvfloat}\
Estudio aerobiológico en la ciudad de Medellín (Colombia): una variable biológica de la calidad del aire en una ciudad altamente contaminada

**Biólogo - Universidad de Antioquia - Medellín, Colombia** \hfill [2011-2018]{.cvfloat}\
Exploración de la utilidad de la región ITS en estudios filogeográficos de plantas de áreas de Páramo

# Otros estudios

**Módulo VII: Foro "Investigaciones en el campo de la etnobiología en Latinoamérica"** \hfill [27 sep 2024]{.cvfloat}\
Comunidad Etnobiológica Guatemalteca, Sociedad Latinoamericana de Etnobiología y Facultad de Ciencias Químicas y Farmacia de la Universidad de San Carlos de Guatemala

**Ciencia Abierta - nivel 2** \hfill [30 ago 2024 – 20 sep 2024]{.cvfloat}\
Universidad de Antioquia

**Ciencia Abierta - nivel 1** \hfill [13 feb 2024 – 09 abr 2024]{.cvfloat}\
Universidad de Antioquia

# Experiencia

**Biólogo-Palinólogo - Universidad de Antioquia** \hfill [feb 2024 – abr 2024]{.cvfloat}\
Análisis palinológico de muestras de suelo provenientes del municipio de Envigado, evidenciando los morfotipos polínicos encontrados en estos suelos, con la finalidad de resolver la posible ocurrencia de actividades agrícolas en el área de estudio.

**Profesor de cátedra - Universidad de Antioquia** \hfill [feb 2023 – jul 2023]{.cvfloat}\
Preparación de clases, calificación de exámenes e informes, atención y asesoría de estudiantes, desarrollo de las prácticas de los laboratorios de biología de las plantas.

**Pasante - Universidad del País Vasco** \hfill [sep 2022 – nov 2022]{.cvfloat}\
Generación de extractos de las esporas de hongos y granos de polen autóctonos más comunes en la atmósfera de la ciudad de Medellín, Colombia, para realizar evaluaciones in-vitro.

**Estudiante instructor - Universidad de Antioquia** \hfill [mar 2019 – nov 2022]{.cvfloat}\
Preparación de clases, calificación de exámenes e informes, atención y asesoría de estudiantes, desarrollo de las prácticas de los laboratorios de biología de las plantas y biología general.

**Auxiliar en curatoría y manejo de colecciones - Universidad de Antioquia** \hfill [sep 2018 – oct 2018]{.cvfloat}\
Curatoría y manejo de colecciones de especímenes botánicos de diferentes proyectos realizados a lo largo de varios años por el Grupo de Estudios Botánicos GEOBOTA del Instituto de Biología de la Universidad de Antioquia.

**Monitor del curso Botánica - Universidad de Antioquia** \hfill [jul 2017 – jun 2018]{.cvfloat}\
Asistencia en campo, asesoría a estudiantes, acompañamiento durante las prácticas de laboratorio, organización y limpieza del laboratorio.

**Monitor del curso Fisiología - Universidad de Antioquia** \hfill [ene 2017 – jun 2017]{.cvfloat}\
Asesoría a estudiantes, acompañamiento durante las prácticas de laboratorio, organización y limpieza del laboratorio.

**Monitor del curso Fisiología vegetal - Universidad de Antioquia** \hfill [jun 2016 – dic 2016]{.cvfloat}\
Asesoría a estudiantes, acompañamiento durante las prácticas de laboratorio, organización y limpieza del laboratorio.

**Monitor del curso Anatomía vegetal - Universidad de Antioquia** \hfill [julio 2015 – junio 2016]{.cvfloat}\
Recolecta de material vegetal, asesoría a estudiantes, acompañamiento durante las prácticas de laboratorio, organización y limpieza del laboratorio.

**Auxiliar de investigación - Universidad de Antioquia** \hfill [ene 2015 – may 2016]{.cvfloat}\
Preparación, procesamiento, obtención, observación y descripción de cortes histológico mediante técnicas histológicas en el proyecto Comparación de la anatomía caulinar de especies del género *Bomarea* Mirb.

**Monitor del curso Biología celular y molecular - Universidad de Antioquia** \hfill [dic 2014 – jun 2015]{.cvfloat}\
Asesoría a estudiantes, acompañamiento durante las prácticas de laboratorio, organización y limpieza del laboratorio.

# Aptitudes

**Campo**
Experiencia en elaboración de colecciones vegetales y en la toma de datos en campo.

**Informática**
Experiencia y conocimiento en el manejo de Sistemas Operativos (iOS, Linux, macOS, Windows), software de ofimática (Google Docs Editors y Microsoft Office), Google Classroom, software bioinformáticos (moleculares y filogenéticos), en lenguaje de programación R, en sistemas de información geográfica (QGIS) y creación de contenido en Quarto y Markdown.

**Laboratorio**
Experiencia en técnicas y métodos palinológicos (obtención, identificación y análisis), de biología molecular (extracción, amplificación, edición y análisis de secuencias de ADN con fines de estudios filogenéticos y poblaciones) e histológicos (obtención, preparación, observación y descripción de tejidos animales y vegetales).

**Otros**
Experiencia en la organización y logística de eventos académicos. Experiencia en la elaboración de inventarios de materiales e insumo de laboratorio (SGA).

# Encuentros 

**XII Congreso Colombiano de Botánica - Popayán, Colombia** \hfill [4-8 nov 2024]{.cvfloat}\
**Ponencia** Influencia de las variables meteorológicas y de los contaminantes atmosféricos sobre el polen aerovagante en Medellín, Colombia

**XII Congreso Colombiano de Botánica - Popayán, Colombia** \hfill [4-8 nov 2024]{.cvfloat}\
**Ponencia** Influencia del cambio climático sobre las concentraciones de polen aerovagante en la ciudad de Medellín, Colombia

**XII Congreso Colombiano de Botánica - Popayán, Colombia** \hfill [4-8 nov 2024]{.cvfloat}\
**Ponencia** ¿Por qué no lo hiciste en Microsoft Word? Cómo hacer una tesis doctoral reproducible usando R y Quarto

**XII Congreso Colombiano de Botánica - Popayán, Colombia** \hfill [4-8 nov 2024]{.cvfloat}\
**Póster** Mapeando los yarumos de Medellín, un proyecto de ciencia ciudadana en mejora de la calidad del aire

**II Simposio del Jardín Botánico de Medellín - Medellín, Colombia** \hfill [19 sep 2024]{.cvfloat}\
**Asistencia**

**XX International Botanical Congress IBC - Madrid, España** \hfill [21–27 jul 2024]{.cvfloat}\
**Póster** How does aerobiology behave in a neotropical city?

**I Simposio del Jardín Botánico de Medellín - Medellín, Colombia** \hfill [26 oct 2023]{.cvfloat}\
**Asistencia**

**XI Congreso Colombiano de Botánica - Villavicencio, Colombia** \hfill [6–10 nov 2022]{.cvfloat}\
**Ponencia** Estudio aerobiológico en la ciudad de Medellín (2019 – 2022)

**XI Congreso Colombiano de Botánica - Villavicencio, Colombia** \hfill [6–10 nov 2022]{.cvfloat}\
**Ponencia** Palinología de sedimentos superficiales como herramienta para la reconstrucción de paleopaisajes en Cundinamarca

**XI Congreso Colombiano de Botánica - Villavicencio, Colombia** \hfill [6–10 nov 2022]{.cvfloat}\
**Póster** Atlas aeropalinológico de Colombia

**XI Congreso Colombiano de Botánica - Villavicencio, Colombia** \hfill [6–10 nov 2022]{.cvfloat}\
**Póster** Catálogo polínico de plantas ornamentales y espontáneas de la Universidad de Antioquia

**X Congreso Colombiano de Botánica - Florencia, Colombia** \hfill [18–22 ago 2019]{.cvfloat}\
**Póster** Utilidad de ITS en estudios filogeográficos de plantas de Páramo

**II Simposio Colombiano en Sistemática y Evolución de Plantas - Medellín, Colombia** \hfill [2–3 ago 2018]{.cvfloat}\
**Ponencia** Utilidad de ITS en estudios filogeográficos de plantas de Páramo

**II Simposio Colombiano en Sistemática y Evolución de Plantas - Medellín, Colombia** \hfill [2–3 ago 2018]{.cvfloat}\
**Logística**

**V Simposio en Ciencias Exactas y Naturales, UdeA - Medellín, Colombia** \hfill [12–15 jun 2018]{.cvfloat}\
**Ponencia** Exploración de la utilidad de la región ITS en estudios filogeográficos de plantas de áreas de Páramo

**I Simposio Colombiano en Sistemática y Evolución de Plantas - Medellín, Colombia** \hfill [23–24 mar 2017]{.cvfloat}\
**Logística**

# Charlas

**Curso de tratamientos taxonómicos y muestreo de plantas** \hfill [22 sep 2023]{.cvfloat}\
Aerobiología: principios y técnicas de muestreo

**Grupo de Alergología Clínica y Experimental GACE** \hfill [7 sep 2023]{.cvfloat}\
Aerobiología de la ciudad de Medellín

**Grupo de Alergología Clínica y Experimental GACE** \hfill [12 dic 2022]{.cvfloat}\
Estudio aerobiológico en la ciudad de Medellín

# Cursos

**Introducción a la Aerobiología - XII Congreso Colombiano de Botánica - Popayán, Colombia** \hfill [4 nov 2023]{.cvfloat}

**Investigación Reproducible con Quarto - XII Congreso Colombiano de Botánica - Popayán, Colombia** \hfill [3 nov 2023]{.cvfloat}

**Etnobotánica Cuantitativa en R  - XII Congreso Colombiano de Botánica - Popayán, Colombia** \hfill [2-3 nov 2023]{.cvfloat}

# Publicaciones

::: {#refs-main}
:::

# Reportes técnicos

::: {#refs-appendix}
:::

# Membresías

**[Grupo de Estudios Botánicos GEOBOTA de la Universidad de Antioquia](https://geobota.github.io)**\
Estudiante de doctorado

**[Asociación Colombiana de Botánica (ACB)](https://asociacioncolombianadebotanica.com)**\
Socio activo

# Referencias

Disponible bajo petición.
