---
title: "XII CCB: Introducción a la Aerobiología"
# subtitle: ""
# description: ""

lang: es

date: 2024-11-04

image: image.svg

citation: true

categories: 
  - Aerobiología
  - Curso
  - Quarto
  - Sito web
  - XII CCB

about:
  id: project
  template: jolla
  image-shape: rectangle
  links:
    - text: "{{< fa brands github >}} GitHub"
      href: https://github.com/geobota/xii-ccb-aerobiologia/
    - text: "{{< fa link >}} Sitio web"
      href: https://geobota.github.io/xii-ccb-aerobiologia/
---

:::{ #project}
:::

Durante el XII Congreso Colombiano de Botánica, realizado entre el 4 y el 8 de noviembre de 2024 en la ciudad de Popayán, Colombia, tuve el placer de dictar el curso «Introducción a la Aerobiología». Este curso representa uno de los primeros acercamientos formales al tema en el país en los últimos años, al menos según los registros disponibles.

Desde finales de 2018, he dedicado mi labor investigativa a la aerobiología, tema que también es el eje central de mi doctorado. Considero fundamental aumentar la difusión y divulgación de esta disciplina en Colombia, un país con una biodiversidad extraordinaria que aún guarda muchos secretos. La falta de redes aerobiológicas consolidadas y de muestreos prolongados en el tiempo limita nuestra comprensión de la interacción entre el aire y los organismos vivos en este contexto único.

La aerobiología tiene un potencial inmenso para el avance científico, particularmente en un país tan biodiverso como el nuestro, donde cada esfuerzo por estudiarla contribuye significativamente al entendimiento de los ecosistemas y a la toma de decisiones informadas.

Toda la información relacionada con el curso está disponible en el [sitio web del curso](https://geobota.github.io/xii-ccb-aerobiologia/).  
